# Defines a host variable.
# If the port changes, only change it here.
@host = http://localhost:8090

### 1. Get status for robot "r1" (with HATEOAS Links)
# @name testGetStatus
GET {{host}}/robots/r1/status

# EXPECTED RESPONSE:
# The JSON now includes a "_links" field pointing to "self" and "actions":
#
# {
#   "id": "r1",
#   "position": { "x": 0, "y": 0 },
#   "energy": 100,
#   "inventory": [],
#   "actionHistory": [],
#   "_links": {
#     "self": { "href": "http://localhost:8090/robots/r1/status" },
#     "actions": { "href": "http://localhost:8090/robots/r1/actions?page=0&size=5" }
#   }
# }


### 2. Generate some actions
### Robot "r1" move up
POST {{host}}/robots/r1/move
Content-Type: application/json

{
  "direction": "up"
}

### Robot "r1" move right
POST {{host}}/robots/r1/move
Content-Type: application/json

{
  "direction": "right" 
}

### Pick up item "diamant"
POST {{host}}/robots/r1/pickup/diamant

### Patch energy for "r1"
PATCH {{host}}/robots/r1/state
Content-Type: application/json

{
  "energy": 80
}

### Robot "r1" attacks robot "r2"
POST {{host}}/robots/r1/attack/r2


### 3. Get paginated actions (Page 1, Size 2)
# Get page 1, with 2 items per page
GET {{host}}/robots/r1/actions?page=1&size=2

# EXPECTED RESPONSE:
# Shows the first two actions ("Moved up", "Moved right")
# "page.number" is 1, "totalPages" is 2 (since 4 actions / 2 per page)
# "hasNext" is true, "hasPrevious" is false.
# A "next" link is present.
#
# {
#   "page": {
#     "number": 1,
#     "size": 2,
#     "totalElements": 4,
#     "totalPages": 2,
#     "hasNext": true,
#     "hasPrevious": false
#   },
#   "actions": [
#     {
#       "id": 1,
#       "action": "Moved",
#       "detail": "up",
#       "timestamp": "...",
#       "links": [
#         { "rel": "self", "href": "http://localhost:8090/robots/r1/actions/1" }
#       ]
#     },
#     {
#       "id": 2,
#       "action": "Moved",
#       "detail": "right",
#       "timestamp": "...",
#       "links": [
#         { "rel": "self", "href": "http://localhost:8090/robots/r1/actions/2" }
#       ]
#     }
#   ],
#   "links": [
#     { "rel": "self", "href": "http://localhost:8090/robots/r1/actions?page=1&size=2" },
#     { "rel": "next", "href": "http://localhost:8090/robots/r1/actions?page=2&size=2" }
#   ]
# }


### 4. Get page 2
GET {{host}}/robots/r1/actions?page=2&size=2

# EXPECTED RESPONSE:
# The next two actions. "hasNext" is false, "hasPrevious" is true.


### 5. Get a single action via its "self" link
GET {{host}}/robots/r1/actions/1

# EXPECTED RESPONSE:
# Only the JSON object for the action with ID 1.

### Check status of "r2" (to see attack result)
GET {{host}}/robots/r2/status

### Test: Get non-existent robot (should return 404)
GET {{host}}/robots/r99/status