spring.application.name=roboterapi

# Ändert den Standard-Port von 8080 auf 8090 (optional)
server.port=8090

# Wir fügen ein paar Beispiel-Roboter beim Start hinzu (nur zur Demo)
robot.initial.count=3